version: '3.4'

networks:
  backend:
    driver: ${NETWORKS_DRIVER:-bridge}

  traefik:
    external:
      name: ${TRAEFIK_NETWORK:-traefik_default}

services:
  apache2:
    tty: true
    build:
      context: ./apache
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: '7.4.10'
        APP_USER_ID: '${APP_USER_ID}'
        APP_GROUP_ID: '${APP_GROUP_ID}'
    volumes:
      - ${APP_PATH}:/var/www/html
    networks:
      - backend
    ports:
      - ${APACHE_PORT}:80

  php-fpm:
    tty: true
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: '7.4.10'
    volumes:
      - ${APP_PATH}:/var/www/html
    networks:
      - backend

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        PHP_VERSION: '7.4.9'
        APP_USER_ID: '${APP_USER_ID}'
        APP_GROUP_ID: '${APP_GROUP_ID}'
    volumes:
      - ${APP_PATH}:/var/www/html
    tty: true
    ports:
      - ${WORKSPACE_PORT}:8000
    networks:
      - backend
      - traefik
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_DOMAIN:-triview.test}"
      - "traefik.docker.network=${TRAEFIK_NETWORK:-traefik_default}"
      - "traefik.enable=true"
      - "traefik.port=80"

  mysql:
    image: mysql:5.7
    environment:
      TZ: ${MYSQL_TIMEZONE:-Asia/Seoul}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH:-.data/mysql}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - backend
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:5
    ports:
      - ${REDIS_PORT:-6379}:6379
    tty: true
    networks:
      - backend
    labels:
      - "traefik.enable=false"
