version: '3.4'

networks:
  backend:
    driver: ${NETWORKS_DRIVER:-bridge}

  traefik:
    external:
      name: ${TRAEFIK_NETWORK:-traefik_default}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${APP_UID:-1000}
        - GID=${APP_GID:-1000}
        - TZ=${APP_TIMEZONE:-Asia/Seoul}
    volumes:
      - ../:/var/www/html:delegated # delegated is for mac user, you don't need it remove them.
      - ~/.composer:/var/www/.composer:delegated
      - ~/.ssh:/var/www/.ssh:delegated
    tty: true
    networks:
      - backend
      - traefik
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_DOMAIN:-triview.test}"
      - "traefik.docker.network=${TRAEFIK_NETWORK:-traefik_default}"
      - "traefik.enable=true"
      - "traefik.port=80"
    extra_hosts:
      - "host.docker.internal:host-gateway" # for mac m1

  mysql:
    image: mariadb:10.4.3
    environment:
      TZ: ${MYSQL_TIMEZONE:-Asia/Seoul}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DATA_PATH:-.data/mysql}:/var/lib/mysql
    ports:
      - ${MYSQL_PORT:-3306}:3306
    networks:
      - backend
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: "mysqladmin ping --silent"
      timeout: 3s
      interval: 1s

